theme = "tale-hugo"
baseURL = "https://interaction.netlify.com/"
languageCode = "en-us"
title = "Persona"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Hakk覺nda"
    title = "Hakk覺nda"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Yaz覺lar"
    title = "Yaz覺lar"
    url = "/post/"
    weight = 0